### ISSUE TITLE
Split symfony bundle required components or move those components to "suggest" in `composer.json`.

### ISSUE THREAD

**Issue by Moln** [doctrine/DoctrineBundle#1110]
I have found that many features can be without of symfony. And using these features in other MVC/ADR (slim, expressive, laravel).
e.g.: **`Command`**, `Dbal`, `Mapping`, `Repository`, `Twig` .

So, Is it possible split these features to new component , or move symfony components to  "suggest" in `composer.json` ?

**Move to `composer.json`'s `suggest`:**

```
    "require": {
        "php": "^7.1",
        "doctrine/dbal": "^2.9.0",
        "doctrine/persistence": "^1.3.3",
        "jdorn/sql-formatter": "^1.2.16"
    },
    "suggest": {
        "symfony/cache": "...",
        "symfony/config": "...",
        "symfony/console": "...",
        "symfony/dependency-injection": "...",
        "symfony/doctrine-bridge": "...",
        "symfony/framework-bundle": "...",
        "symfony/service-contracts": "..."
    }
```

**Comment by ostrolucky** [comment]
No, I don't think it makes sense to use symfony bundle without symfony. What's your use case and why can't you use dbal/orm without bundle?

**Comment by alcaeus** [comment]
To elaborate on what Gabriel said, this bundle is to integrate the DBAL/ORM into Symfony. The idea is to have a smooth integration into the framework. To that effect, we'd prefer to have specific framework integrations for frameworks that use ORM to make sure the developer experience is what they've come to expect from their framework of choice.

We've previously done this for Zend Framework, but these have not seen lots of attention due to the lack of users. If you are willing to work on a framework integration, we'd be happy to help. We are short on maintainers, so if you want a specific integration to be under the Doctrine umbrella, it would have to come with a commitment to maintain it.

I'm closing this issue here as this is not something we can do in the bundle. Please feel free to pop into the Doctrine Slack at https://doctrine.slack.com and either ping me or talk to us in the #general channel about this. Thanks!
