### ISSUE TITLE
Add ability to assign your own SQLLogger

### ISSUE THREAD

**Issue by rjd22** [doctrine/DoctrineBundle#1280]
At this moment adding your own SQL logger is not possible because the set is fixed.

I've been working on the implementation of the Sentry Performance integration and after a lot of poking and prodding there just doesn't seem to be a way to do this nicely. So I had to come up with trickery by replacing the DbalLogger.

Would it be acceptable for you to give an PR that allows you to set your own custom logger next to the DbalLogger?

Link to sentry PR:
https://github.com/getsentry/sentry-symfony/pull/426

**Comment by ste93cry** [comment]
It looks like this is already supported when configuring the `logging` option of the connection.

https://github.com/doctrine/DoctrineBundle/blob/6a4b9589b9df7061cb2e9afa0c3d3c3d57611d38/DependencyInjection/DoctrineExtension.php#L154-L163

**Comment by rjd22** [comment]
@ste93cry All these loggers are non configurable. And as soon as the loggerChain is made there isn't a possibility to add another logger because the addLogger method is deprecated. As you can see in the later version of the Extension:

https://github.com/doctrine/DoctrineBundle/blob/015fdd490074d4daa891e2d1df998dc35ba54924/DependencyInjection/DoctrineExtension.php#L162-L180

Another problem is for the loggerChain to work you need to enable `dbal.profiling` what also enables the `DebugStack` and `BacktraceLogger`. This is most likely something you want to avoid on production.

Only setting `dbal.logging` enables the `DbalLogger` that can be easily replaced. But it would be better if we could set a loggerChain so that a developer can decide to replace it or add another logger.

Thank you for checking up on this, I could really use another pair of eyes on thing issue.

**Comment by ste93cry** [comment]
>And as soon as the loggerChain is made there isn't a possibility to add another logger because the addLogger method is deprecated

That should not be an issue, we can always edit the argument of the constructor in our compiler pass to add the logger, even though it would be nicer if the services were tagged so that we could use `!tagged` in the service definition

>Another problem is for the loggerChain to work you need to enable `dbal.profiling`

You're definitely right, I totally missed the wrapping `if ($connection['profiling']) {` statement. I see two ways to solve the issue: either we change the implementation here to always use the `LoggerChain` logger, or in our own compiler pass in Sentry we enforce that the logger is always a `LoggerChain`

**Comment by rjd22** [comment]
@ste93cry my recommendation would be to add an extra configuration option where you can set the loggers you want to attach when logging is enabled that contains the DbalLogger by default.

This will make it easy for the developer to attach an extra logger or replace the DbalLogger when enabling logging per connection.

**Comment by ostrolucky** [comment]
Yes, this is welcome. [I've put building blocks for this feature one year ago](https://github.com/doctrine/dbal/pull/3572) - with that I expected that providing this feature would be trivial. This is [not the first time we got such request ](https://github.com/doctrine/DoctrineBundle/issues/225), we even [had a PR adding this](https://github.com/doctrine/DoctrineBundle/pull/692), but was rejected because of various reasons. What we expect here though is not adding more configuration options, but having `doctrine.dbal.logger` tag. DoctrineBundle then automatically picks up everything tagged as such via `!tagged`.

I'm also up to dropping dbal 2.9.0. Only reason compatibility layer with dbal 2.9 was added was because DBAL 3.x support was already present in doctrine-bundle 1.12.x, but was incomplete/broken and needed fixing.

The only things that could be tricky (this was also a problem in https://github.com/doctrine/DoctrineBundle/pull/692) is handling of `dbal.connections.*.logging`, because it means we can neither register profiling/backtrace loggers into main chain logger, nor clear existing tags, as it would affect all connections. But I'll leave that up to whoever creates PR to solve it.

**Comment by rjd22** [comment]
Do you mean with the tricky part, that you need the ability to assign a logger per connection?

Can't we solve this by adding an argument to the tag that contains the connection you want to add the logger to and else if it's empty to logger will be added to all connections?

Do I understand this correctly?

**Comment by ostrolucky** [comment]
Yes to all

**Comment by ostrolucky** [comment]
Hmm actually we cannot drop DBAL < 2.10, because 2.10 requires PHP 7.2 :(

**Comment by rjd22** [comment]
@ostrolucky Well I've read the PR that was not merged, I feel that to make it work nicely we need to rebuild the whole logger attach section. This is not a trivial amount of work.

I also wonder if you want to attach all loggers with a tag. So also the DbalLogger and profiler loggers. If so it might be unavoidable to attach the ChainLogger even if we only have one logger. I wonder if that is acceptable because it would keep things move consistent overall, with the downside of a really small overhead.

Edit:
To be honest I kind of feel the whole logger section is kind of a mess, all to avoid attaching the ChainLogger when there is only one logger. Also I think that it would serve the developer better if we make the ChainLogger independent of the `logging` option since developers might want to attach a logger but not enable logging itself.

**Comment by ostrolucky** [comment]
Yes, having ChainLogger always registered is acceptable. Also, I think we cannot use tagged_iterator in the end, because it would register all loggers no matter the connection :/ So I think we will have to go old fashioned way, where we iterate over tagged services in compiler pass ourselves - ther we can read connection attribute of the tag.

> I think that it would serve the developer better if we make the ChainLogger independent of the logging option since developers might want to attach a logger but not enable logging itself.

I think I agree. So perhaps attach `doctrine.dbal.logger` tag to `doctrine.dbal.logger` only if `logging` is enabled, but attach all the other services with such tags no matter the option?

**Comment by rjd22** [comment]
@ostrolucky The section where I just can't wrap my head around is the following section. It seems that the logger is attached to the logger chain but never used for default connections. But I feel that this is not possible:

https://github.com/doctrine/DoctrineBundle/blob/015fdd490074d4daa891e2d1df998dc35ba54924/DependencyInjection/DoctrineExtension.php#L88-L99

**Comment by ostrolucky** [comment]
Indeed, looks like logging doesn't work unless profiling is enabled. And code you quoted looks ineffective since https://github.com/doctrine/DoctrineBundle/commit/2c377e26e8f54590dbacd0e8d49c10666c354860#diff-afe5f060789287a8ad428a4b5df1ad844184f496ece0297e421f6b1fc442b5a4L146. Until then, ChildDefinition was used

**Comment by ostrolucky** [comment]
@rjd22 any update? did you give up on this?

**Comment by rjd22** [comment]
@ostrolucky to be honest I have not been working on this. For Sentry we've gone a different way because we wanted access to more information. So we wrapped the connection.

Since I lost my personal need for this I don't think I will work on this anymore. So if someone else wants to pick this up it's okay to do so.

**Comment by ste93cry** [comment]
Since I believe that this improvement would be useful, I may be able to work on it in the next weeks. @ostrolucky feel free to take it if you want of course, otherwise I would leave this issue open for a bit more time. If for any reason should you start working on it, please let me know so that we don't do the work twice 😄

**Comment by ostrolucky** [comment]
Solved by https://github.com/doctrine/DoctrineBundle/pull/1472
