### ISSUE TITLE
Unix socket is not being used

### ISSUE THREAD

**Issue by trsteel88** [doctrine/DoctrineBundle#1372]
I have recently noticed that the unix socket is not being used when specified through a DSN.

e.g:

```
mysql://username:password@127.0.0.1/db?unix_socket=/tmp/mysql.sock
```

I have noticed this because if you change 127.0.0.1 to something else:

```
mysql://username:password@something-made-up/db?unix_socket=/tmp/mysql.sock
```

It results in an error.

I have also tried the following:

- mysql://username:password/db?unix_socket=/tmp/mysql.sock
- mysql://username:password@/db?unix_socket=/tmp/mysql.sock

Have I configured the DSN wrong or is this a bug?

**Comment by dmaicher** [comment]
Indeed seems like this is not supported via the `url` option. 

However semantically its also a bit tricky since the url has a host and you don't want to use one but use a socket instead :yum: 

Had a look and its not supported on DBAL as far as I can tell: https://github.com/doctrine/dbal/blob/3.1.x/src/DriverManager.php#L294

**Comment by dmaicher** [comment]
Closing for now as I don't think its an issue on the Bundle. Its not supported by DBAL from what I can tell. Let me know if you think differently.
