### ISSUE TITLE
Documentation missing Event Listener 'Full example'

### ISSUE THREAD

**Issue by zpottie** [doctrine/DoctrineBundle#1463]
Hi there,

First issue, so let me know if you need anything else. 😄 

It looks like the documentation isn't displaying properly on Symfony's site - not sure if this should actually raised with them...

This file here:
https://github.com/doctrine/DoctrineBundle/blob/2.6.x/Resources/doc/entity-listeners.rst#entity-listeners

Does not have the first 'Full example' showing on Symfony's site:
https://symfony.com/doc/current/DoctrineBundle/entity-listeners.html

Because I was using the Event Listeners for the first time, the missing example caused me to have to scour the internet (without success) until I actually found the file here in the repo (I didn't realise the example was missing, initially).

Let me know if I can do anything. 👍 

Thanks!

**Comment by dmaicher** [comment]
Indeed the example does not show up :thinking: 

Any idea  @ostrolucky @stof ? 

For 1.12.x it shows up: https://symfony.com/bundles/DoctrineBundle/1.12.x/entity-listeners.html

However there it was not using `.. configuration-block::` with `annotation` and `attribute`

Edit: [here](https://www.doctrine-project.org/projects/doctrine-bundle/en/2.4/entity-listeners.html#entity-listeners) it shows up fine

**Comment by stof** [comment]
@javiereguiluz maybe you have some insights why this does not show up on symfony.com

**Comment by javiereguiluz** [comment]
This is caused by some RST syntax issues that prevent the building of the docs (and since the docs are not built, the bundle is unpublished from the web).

The main issue I see is the usage of `.. code-block:: annotation` instead of `.. code-block:: php-annotations`

Here you can see the detail about the syntax issues for all versions of this bundle: https://symfony.com/doc/build_errors#doctrine-bundle-1.3
