### ISSUE TITLE
Extends DoctrineOrmMappingsPass since 2.9

### ISSUE THREAD

**Issue by AurelienPillevesse** [doctrine/DoctrineBundle#1655]
I'm looking to this bundle and we can see that : `class RegisterDoctrineOrmMappingPass extends DoctrineOrmMappingsPass` (https://github.com/thephpleague/oauth2-server-bundle/blob/master/src/DependencyInjection/CompilerPass/RegisterDoctrineOrmMappingPass.php)

But in this bundle, since 2.9, `DoctrineOrmMappingsPass` is final. (https://github.com/doctrine/DoctrineBundle/blob/2.9.x/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php)

What would be the right way to keep this bundle working for DoctrineBundle version 2.9?

**Comment by stof** [comment]
Use the class of DoctrineBundle directly by passing the right constructor argument instead of creating a child class that only hides the constructor arguments passed to the parent.

Side note: the bundle still works with DoctrineBundle 2.9 as the class is not final yet. It will become final only in 3.0. For now, you only get a deprecation warning.
