### ISSUE TITLE
The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.

### ISSUE THREAD

**Issue by ecwio** [doctrine/DoctrineBundle#1811]
symfony 7.1
doctrinebundle 2.12.0
dbal 4.0.4
doctrine/orm: 3.2.1

```
docker exec -ti postgres psql --version
psql (PostgreSQL) 15.3 (Debian 15.3-1.pgdg120+1)
```

symfony doctrine.yaml
```
doctrine:
    dbal:
        url: "postgresql://app:pass@postgres:5432/dev?serverVersion=15.3 (Debian 15.3-1.pgdg120+1)&charset=utf8"
```

error:
```
The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
```

running `docker exec -ti app php bin/console doctrine:migrations:sync-metadata-storage` does not fix the issue

I tried 
- url: "postgresql://app:pass@postgres:5432/dev?serverVersion=15.3&charset=utf8"
- url: "postgresql://app:pass@postgres:5432/dev"
- clearing cache
-  using discrete parameters instead of url
```
doctrine:
    dbal:
        server_version:    '15.3 (Debian 15.3-1.pgdg120+1)'
        dbname:            'dev'
        host:              'postgres'
        port:              5432
        user:              'app'
        password:          'pass'
        driver:            'pdo_pgsql'
        charset:           'utf8'
```

**Comment by ostrolucky** [comment]
Unfortunately this is not something that can be acted upon by doctrine-bundle maintainers, as issue is most likely somewhere outside of it. Once you provide information which points out issue is in doctrine-bundle, we can then reopen. But until then, I would recommend to investigate issue more deeply so that you know in which vendor package issue is, or open the issue on stack overflow etc.
