### ISSUE TITLE
Latest version in packagist is still 1.5.1

### ISSUE THREAD

**Issue by sbacelic** [doctrine/DoctrineBundle#458]
Maybe refresh packagist cache? :bow:

**Comment by aeyoll** [comment]
This is still the case today, can someone fix this please? Thanks!

**Comment by iszak** [comment]
:+1:

**Comment by stof** [comment]
@beberlei can you check whether the repository hook is configured properly (or give me admin access on this repo and maintainer access on packagist so that I can handle such things myself) ?

**Comment by stof** [comment]
I think I know what it is. The tag was pushed after pushing commits, and so pushing it was not triggering a ``push`` webhook on github because there was no new commit and no branch update.
Given no commit was done in the repo since then, no update was triggered on Packagist. @beberlei can you trigger a manual update on Packagist ?

**Comment by Restless-ET** [comment]
Looks like it's already solved. :+1:  (it's working for me at least)
