### ISSUE TITLE
[RFC] Updating the Doctrine commands for the new style guide

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#466]
We want to update all Symfony commands to use [the new style guide](https://github.com/symfony/symfony/pull/14057) and we want to do that before the "feature freeze" period starts in two days.

My question is: if I create some pull requests udpdating the Doctrine commands, will they be accepted?(assuming they are technically correct of course)

**Comment by stof** [comment]
There is 2 things to take care about:

- most commands are in the ORM itself, not in the bundle. So this will depend on the ORM team, not on me
- I don't want to drop support for Symfony 2.3 until it reaches the end of support. otherwise I would have to maintain 2 versions of the bundle (as shipping an unmaintained bundle in the SE is not an option) and I would like to avoid that.

**Comment by stof** [comment]
btw, this is not required to be done before the Symfony feature freeze though: Doctrine feature freeze does not happen at the same time.

**Comment by ostrolucky** [comment]
As @stof mentioned there aren't many commands to update in doctrine bundle itself, but of course this contribution would be welcome. 

@javiereguiluz are you still interested in this? Sorry for not getting to you not sooner!

**Comment by greg0ire** [comment]
I think @OskarStark took care of the ORM part: https://github.com/doctrine/orm/pull/6655

**Comment by alcaeus** [comment]
Better late than never: no logic here to take care of. Closing.

**Comment by ostrolucky** [comment]
I wouldn't say no logic, we have eg. `doctrine:database:create`, `doctrine:database:drop` etc so if anybody wants to update it, feel free.
