### ISSUE TITLE
Merge the "doctrine_pretty_query" and "doctrine_highlight_sql" Twig filters

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#469]
As @stof commented in https://github.com/doctrine/DoctrineBundle/pull/452#discussion_r40557258

> well, this method does exactly the same than the new doctrine_highlight_sql, except that one is using the profiler styles and the other one uses the raw SqlFormatter colors. This looks weird to me.

**Comment by stof** [comment]
@javiereguiluz It would be great to solve this soon, so that we don't release a version with this inconsistency.

**Comment by stof** [comment]
@javiereguiluz any plan to work on this ?

**Comment by javiereguiluz** [comment]
I've taken a look at this and I'm not sure we can merge both filters:

  * `doctrine_pretty_query` formats the query and highlights it.
  * `doctrine_highlight_sql` only highlights the given query.

The output of both filters is completely different ... and we need both (one for the "Show Formatted" link and the other for the regular query display).

**Comment by stof** [comment]
@javiereguiluz both are formatting it under the hood. But one of them displays it in a ``<pre>`` tag (so that formatting is preserved in HTML) while the other one replaces it by a ``<div>`` (loosing indentation and newlines from the display).
And the other differences is that one of them uses the profiler CSS classes for highlighting colors, while the other keeps the inline styles of the library (well, not even true: it depends whether ``doctrine_highlight_sql`` was called before or not, because of the global state change)
