### ISSUE TITLE
[Symfony 2.7.5] The 'doctrine:generate:entities' command requires database connection.

### ISSUE THREAD

**Issue by zacharyzh** [doctrine/DoctrineBundle#474]
doctrine:generate:entities:    Generates entity classes and method stubs from your mapping information

When I use this command to generate setter and getter methods (LOCAL, my mac, **without MySQL**):

    ./console doctrine:generate:entities AppBundle

I got this message:

    [Doctrine\DBAL\Exception\ConnectionException]
    An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused

***MySQL was installed on server only***

This bug does not exists in previous versions of Symfony.

Sorry for my bad english.

**Comment by zacharyzh** [comment]
hello? is anyone here?

**Comment by stof** [comment]
This is because DBAL 2.5 detects the version of MySQL being used, to better support differences between mysql versions. If you don't have a MySQL server to connect to, it will not be able to determine this. A solution is to configure the ``server_version`` in your connection configuration, to tell DBAL what your MySQL version is instead of relying on guessing.

New projects created on older versions of Symfony were shipping with Doctrine DBAL 2.4 by default.

**Comment by zacharyzh** [comment]
Oh, I see. Thank you very much, @stof .
