### ISSUE TITLE
Remove doctrine/doctrine-cache-bundle as dependency

### ISSUE THREAD

**Issue by Tobion** [doctrine/DoctrineBundle#491]
The doctrine bundle has the doctrine/doctrine-cache-bundle as requirement: https://github.com/doctrine/DoctrineBundle/blob/master/composer.json#L33

I think it's because of historic reasons when doctrine bundle also included caching. But with doctrine bundle 1.3, the caching got extracted to it's own bundle. But this dependency makes no sense anymore and we should get rid of it.

People need to add the cache bundle manually to the AppKernel anyway.

**Comment by stof** [comment]
This dependency has been **added** when creating doctrine/doctrine-cache-bundle, so that we can reuse the classes of DoctrineCacheBundle to create cache services based on the DoctrineBundle config instead of having to maintain exactly the same logic in DoctrineBundle (and then missing the support for new cache providers).

If we want to remove this dependency, it means we would have to break BC in the configuration by forcing to pass a service id or a cache provider name only for the query/result/metadata caches.
and a drawback of telling people to use an id is that they might reuse the same cache service for all of them, or for multiple entity managers, which could break things because of cache key collisions (reusing the same cache for multiple entity managers is guaranteed to break, as the cache key for the metadata cache is based only on the class name for instance, not on the way the EM is configured, which would become insane to implement)
