### ISSUE TITLE
[DX][Profiler] Show where the query was made

### ISSUE THREAD

**Issue by MacDada** [doctrine/DoctrineBundle#525]
It is sometimes tedious to find what caused the exact query, visible in `Doctrine` panel, to be run.

It would be cool if next to `Explain query` button there was a `Show stacktrace` button. Even if it would be visible only for people with Xdebug enabled.

**Comment by stof** [comment]
This has already been suggested in the past, and the change necessary for that in DBAL has been rejected. I will let you read https://github.com/doctrine/DoctrineBundle/pull/275 and https://github.com/doctrine/dbal/pull/535 for the discussion about this.

I'm closing this issue as rejected.

**Comment by sustmi** [comment]
Just for reference, this feature is already available in Doctrine bundle: https://symfony.com/blog/new-in-doctrinebundle-1-11-0#store-backtraces-when-profiling-queries (PR: https://github.com/doctrine/DoctrineBundle/pull/954) .

You just need to enable it by setting `doctrine.dbal.profiling_collect_backtrace: true` (I set it to `'%kernel.debug%'` instead because it is the default value of `profiling` setting that this feature depends on).

Web search got me here and from this conversation it looks like it may not be available yet.

**Comment by morphles** [comment]
@sustmi you'r comment is just amazing! Super duper thanks!
