### ISSUE TITLE
Class of "doctrine.dbal.connection" service is not configurable by a parameter

### ISSUE THREAD

**Issue by slootjes** [doctrine/DoctrineBundle#537]
Almost every class in the dbal.xml has to option to be set by a parameter which is awesome! However the one I need to modify is not available to set: doctrine.dbal.connection. Can the "doctrine.dbal.connection.class" parameter be added so I can extend the default Connection with a few extra functions? It's so simple that I don't think a PR is needed for it but of course I'm willing to create one.

**Comment by kimhemsoe** [comment]
Try to take a look at dbal wrapperClass option and see if that does not give you what wish.

http://symfony.com/doc/current/reference/configuration/doctrine.html
http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/configuration.html#wrapper-class

**Comment by stof** [comment]
Symfony stopped using parameters for classes, because we found out that it is almost always a broken extension point (as your class has to accept the same service configuration than the original one, including when the bundle changes how the configuration looks like).
So I won't add new class parameters in the bundle (and the day when I move to 2.0, I will remove existing ones, but this won't happen soon as this change alone is not worth doing a major version).

**Comment by slootjes** [comment]
Thanks for explaining this so quickly. I'll look at the wrapper class,  it looks promising :)
