### ISSUE TITLE
Is there any way to skip readonly entity in  ./bin/console doctrine:schema:update --force

### ISSUE THREAD

**Issue by skornev** [doctrine/DoctrineBundle#564]
Or maybe there is another option? I would like to skip read only entites(which are views) from being created by that command.

**Comment by mikeSimonson** [comment]
If the read only entities are managed by a [different entity manager instance.](http://symfony.com/doc/current/doctrine/multiple_entity_managers.html)
Then you can pass the default manager explicitly to the command and it will ignore those readonly entities.

**Comment by stof** [comment]
Read-only entities in Doctrine ORM are not meant to handle views, because they are not really read-only: they can still be inserted and deleted. the only difference is that they are not tracked for updates.
The name ``read-only`` is totally misleading. It is unfortunate that Doctrine reused the same naming that Hibernate when implementing the same concept.
``immutable`` would be a much better name for this flag.
This naming confusion is the source of almost all issues opened about read-only entities since they have been introduced in Doctrine, because almost everyone misunderstands what this feature is about.

**Comment by stof** [comment]
@mikeSimonson using a separate manager to handle the read-only entities has a huge impact on the usage of Doctrine, probably defeating the point of using them altogether.

**Comment by skornev** [comment]
stof  Yes,  I know. 
As for immutable. Does it mean we have to have immutable PHP objects also?

**Comment by stof** [comment]
Well, it is not mandatory, as long as you are aware that doing changes in the object after it was loaded from the DB will never make Doctrine persist the changes. But making PHP entities immutable in this case is generally a good idea to avoid mistakes (where you would forget that updates are ignored).
The main use case for this flag is precisely to persist immutable object (btw, Hibernate turns the flag on automatically when the entity class is immutable, as Java has such a concept).

**Comment by kimhemsoe** [comment]
Closing as not a bundle issue. If it is a feature request it should be created for the ORM.

**Comment by stof** [comment]
@kimhemsoe even as a feature request on the ORM, it should be rejected, for the reason given in https://github.com/doctrine/DoctrineBundle/issues/564#issuecomment-241415479

**Comment by kimhemsoe** [comment]
@stof I meant for real "read only" entities, view support or something down that road. Not for skipping entities :)
