### ISSUE TITLE
Unknown "profiler_dump" function in "DoctrineBundle:Collector:db .html.twig"

### ISSUE THREAD

**Issue by picks44** [doctrine/DoctrineBundle#611]
I've been facing this error while I deploy my app recently 
```
[2017-02-01 14:19:27] assetic.ERROR: The template "DoctrineBundle:Collector:db.html.twig" contains an error: Unknown "profiler_dump" function in "DoctrineBundle:Collector:db
.html.twig" at line 241.
```

Any clue ?

**Comment by stof** [comment]
Well, this is because this function is only registered when using the WebProfilerBundle (but the template is only used in this case too).

This seems to happen during the AsseticBundle cache warmup. A solution to fix this is to use the AsseticBundle feature allowing to restrict the bundles being checked for Assetic tags (there is not usage of Assetic in the templates of DoctrineBundle)

**Comment by picks44** [comment]
Well received! I removed the option because it disappeared from the documentation when I upgraded from SF2.7 to 2.8... Thanks!

**Comment by stof** [comment]
this is an issue in the doc then, which you should report to the symfony-docs repo. AsseticBundle has not removed this setting
