### ISSUE TITLE
[defect] An error is encountered when saving the data due to an optional association

### ISSUE THREAD

**Issue by slince** [doctrine/DoctrineBundle#612]
DDL:
```
create table articles(
     id int(10) not null auto_increment primary key comment 'id',
     title varchar(200) not null default '' comment 'post title',
     category_id int(10) not null default 0 comment 'category'
);

create table categories(
     id int(10) not null auto_increment primary key comment 'id',
     name varchar(200) not null default '' comment 'name'
);
```

Expect:
`Article` OneToMany `Category`, (<b>optional</b>, If an article does not belong to any of the categories, then `category_id` is 0 ) 

What i did:
```
$article = new Article();
$article->setTitle('This is a test article');
//...
$em->persist($article);
$em->flush();
```
What happed:
   Error
```
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null



  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null
```

PS: I can not set category_id to null because DBA does not allow,
> Do not set the field to null for mysql

**Comment by Ocramius** [comment]
This is quite expected: you need a category for an article, and should probably enforce that in the `Article` constructor as required parameter.

Closing, since this is:
 * not an issue
 * invalid code in your domain

**Comment by slince** [comment]
@Ocramius  You may not understand my problem,  <b>Article does not necessarily have category</b> ,This is business needs

**Comment by slince** [comment]
> Expect:
Article OneToMany Category, (<b>optional, If an article does not belong to any of the categories, then category_id is 0 )</b>

**Comment by Ocramius** [comment]
```sql
create table articles(
     id int(10) not null auto_increment primary key comment 'id',
     title varchar(200) not null default '' comment 'post title',
     category_id int(10) not null default 0 comment 'category'
);
```

This is very clear to me: `category_id` cannot be null, therefore an article **ALWAYS** has a category (with category `0` being assigned by default).

I know this sounds harsh, but tell your DBA to [learn what `NULL` means in SQL RDBMSs](https://stackoverflow.com/questions/15502408/doctrine-2-use-default-0-values-instead-of-null-for-relation).

**Comment by slince** [comment]
Well, This is a production project based on cakephp, there are many category_id 0 data,  Dba will not easily change the data table.  I think doctrine should be more flexible, since doctrine should serve the project, doctrine now cart before the horse

**Comment by Ocramius** [comment]
>  I think doctrine should be more flexible

No, this was discussed before in the ORM and DBAL projects, and doctrine follows SQL semantics on FK integrity, or else we just open a can of worms, and consistency becomes a war field.
If you want to fix this on your side, use the null object pattern and actually create `0` records in your DB.

Note that you are currently hitting issues during `INSERT` operations, but doctrine ORM will also crash during `SELECT` operations due to your FK integrity constraints being invalid/broken.

**Comment by slince** [comment]
0.o  
> What NULL means in SQL RDBMS

Your know, any columns have a clear type, `number` or `string`; but `null` does not represent any type; an `number` type  field should be "0" for "no value", string type field with "empty string" that "no value"


PS: My DBA told me that

**Comment by slince** [comment]
@Ocramius

**Comment by Ocramius** [comment]
> Your know, any columns have a clear type, number or string; but null does not represent any type; an number type field should be "0" for "no value", string type field with "empty string" that "no value"

@slince `NULL` represents the absence of a value, while:

 * `''` is a value of type `string`
 * `0` is a value of type `integer`
 * "[]" is an empty array for a `json`
 * etc.

In SQL RDBMSs, unless you design your own FK policy (don't do it), `NULL` is the "unchecked" value, since **no value** is present, and value integrity integrity checks don't apply.

In your case, CakePHP entirely skipped over the whole "data integrity" part, because it was probably designed to work [only on MyISAM, where FK integrity and cascade operations don't really work](https://stackoverflow.com/questions/12971246/why-doesnt-mysqls-myisam-engine-support-foreign-keys).

This is not something doctrine can fix for you, since there are basic data integrity violations in your DB, and doctrine expects the DB to be in a consistent state.
Introducing support for "broken" FK references in doctrine would just lead to more problems, while the root of your issue is quite clear

**Comment by slince** [comment]
Yeah, We do not use mysql foreign keys, we only define the foreign key business; DBA that the foreign key will reduce the efficiency of mysql, we only use foreign keys on the oracle. But we use the innodb engine for mysql.

**Comment by slince** [comment]
How do I feel your theory and our DBA is exactly the opposite

**Comment by Ocramius** [comment]
@slince there is evidently a big difference between what the ORM can do, and what your DBA wants it to support.

I clarified the reasoning, and this is not landing in doctrine anytime in the next few years: if you can't fix the schema, all I can tell you is that introducing Doctrine ORM will likely create more problems than what it's supposed to be fixing for you.

**Comment by slince** [comment]
It is really regrettable. I'm a fan of symfony and doctrine, but now I have to tell my leader that I can only use cakephp to develop new projects. I began to understand why [sylius](https://github.com/sylius) and bamboo do not use doctrine orm but dbal;

Finally I suggest that doctrine should be guaranteed compatibility as much as possible and you have to admit that there are a lot of databases that are very old. Theory is no more than practice， Practical is the first

best wishes

@Ocramius

**Comment by Ocramius** [comment]
@slince doctrine ORM is designed for an object-model first, db second. It doesn't fit every model, nor should. Always keep the 80/20 split in mind.
