### ISSUE TITLE
Is OneToOne with UUID working properly?

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [doctrine/DoctrineBundle#671]
DoctrineBundle Version: 1.6.8

Ps: It's supposed to be a unidirectional OneToOne
Ps2: I'm kindda new to Doctrine so, if it's a stupid mistake of mine, I'm sorry in advance.

es_course:
```
class Course {
    /**
     * @var string
     *
     * @ORM\Column(name="id", type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;
```

game:
```
class Game {
    /**
     * @var Course
     *
     * @ORM\OneToOne(targetEntity="EBundle\Entity\Course")
     * @ORM\JoinColumn(name="t_course", referencedColumnName="id", nullable=true)
     */
    private $tcourse = null;
```

SqlDump:
```
ALTER TABLE game ADD CONSTRAINT FK_C1E5C5CF3FF91747 FOREIGN KEY (t_course) REFERENCES es_course(id);
CREATE UNIQUE INDEX UNIQ_C1E5C5CF3FF91747 ON game(t_course);
```

Validate
```
[Mapping]  OK - The mapping files are correct.
[Database] FAIL - The database schema is not in sync with the current mapping file.
```

Created Tables:
es_course.id -> VARCHAR(255)
game.t_course -> CHAR(36)

Trace after executing Schema:Update :
```
 [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE game ADD CONSTRAINT FK_C1E5C5CF3FF91747 FOREIGN KEY (t_course) REFERENCES es_course(id)':
  SQLSTATE[HY000]: General error: 1005 Can't create table 'ldgame.#sql-456_d8' (errno: 150)

Exception trace:
 () at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
 Doctrine\DBAL\Connection->executeQuery() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:843
 Doctrine\ORM\Tools\SchemaTool->updateSchema() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:133
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:65
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at /var/www/vendor/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:50
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:868
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /var/www/app/console:27
```

**Comment by Ocramius** [comment]
Doctrine 1.6.8?
Also, try specifying the column type on your @JoinColumn

On 9 Jun 2017 21:55, "Marcelo Petrucelli" <notifications@github.com> wrote:

Well, actually I have a similar problem:
Doctrine Version: 1.6.8

Ps: It's supposed to be a unidirectional OneToOne
Ps2: I'm kindda new to Doctrine so, if it's a stupid mistake of mine, I'm
sorry in advance.

es_course:

class Course {
    /**
     * @var string
     *
     * @ORM\Column(name="id", type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;

game:

class Game {
    /**
     * @var Course
     *
     * @ORM\OneToOne(targetEntity="EBundle\Entity\Course")
     * @ORM\JoinColumn(name="t_course", referencedColumnName="id",
nullable=true)
     */
    private $tcourse = null;

SqlDump:

ALTER TABLE game ADD CONSTRAINT FK_C1E5C5CF3FF91747 FOREIGN KEY
(t_course) REFERENCES es_course(id);
CREATE UNIQUE INDEX UNIQ_C1E5C5CF3FF91747 ON game(t_course);

Validate

[Mapping]  OK - The mapping files are correct.
[Database] FAIL - The database schema is not in sync with the current
mapping file.

Created Tables:
es_course.id -> VARCHAR(255)
game.t_course -> CHAR(36)

Trace after executing Schema:Update :

 [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE game ADD
CONSTRAINT FK_C1E5C5CF3FF91747 FOREIGN KEY (t_course) REFERENCES
es_course(id)':
  SQLSTATE[HY000]: General error: 1005 Can't create table
'ldgame.#sql-456_d8' (errno: 150)

Exception trace:
 () at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at
/var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at
/var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
 Doctrine\DBAL\Connection->executeQuery() at
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:843
 Doctrine\ORM\Tools\SchemaTool->updateSchema() at
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:133
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand()
at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:65
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute()
at /var/www/vendor/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:50
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute()
at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at
/var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:868
 Symfony\Component\Console\Application->doRunCommand() at
/var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at
/var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at
/var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /var/www/app/console:27

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/DoctrineBundle/issues/671>, or mute the thread

**Comment by Marcelo-Petrucelli** [comment]
Oh, sorry about that, I meant DoctrineBundle Version =X

When I try to add a Type to the @JoinColumn I get the following message:

```
[Doctrine\Common\Annotations\AnnotationException]
  [Creation Error] The annotation @ORM\JoinColumn declared on property AptorGames\EntitiesBundle\Entity\Game::$tcourse does not have a property nam
  ed "type". Available properties: name, referencedColumnName, unique, nullable, onDelete, columnDefinition, fieldName
```

**Comment by Ocramius** [comment]
What are, respectively, the ORM and DBAL versions?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Marcelo-Petrucelli** [comment]
Hi again Ocramius. Thanks for your replies. Here are my ORM and DBAL versions

ORM: v2.5.6
DBAL: v2.5.12

**Comment by Ocramius** [comment]
Could you please try ORM master and report whether it works there?

**Comment by Marcelo-Petrucelli** [comment]
Sure. I let you know as soon as I try it!

**Comment by Marcelo-Petrucelli** [comment]
Just for the sake of testing, I've also tried "2.5.x-dev", which worked with PHP5.6, according to Packagist. But the problem persists.

**Comment by Marcelo-Petrucelli** [comment]
Well... after more digging, I got a pretty strange problem, that is not really related with DoctrineBundle.

My temporary solution for the Char(36) and Varchar(255) was basically this:
```
    /**
     * @var Course
     *
     * @ORM\OneToOne(targetEntity="EBundle\Entity\Course")
     * @ORM\JoinColumn(name="t_course", referencedColumnName="id", columnDefinition="VARCHAR(255)", nullable=true)
     */
    private $tcourse = null;
```

After that my problem persisted, therefore it was probably something else (not type mismatch). To figure it out, I tried to run the SQL from --dump-sql by hand on mysql. Same error message, but after using:
`SHOW ENGINE INNODB STATUS;`

I finally found my problem, which is related to the project:
```
Error in foreign key constraint of table ldgame/#sql-d89_79:
 FOREIGN KEY (t_course) REFERENCES ldgame.escola_course (id):
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
See http://dev.mysql.com/doc/refman/5.5/en/innodb-foreign-key-constraints.html
for correct foreign key definition.
```

I'd still verify if there was any changes from VARCHAR(255) to CHAR(36) as the default for UUIDs. Since this project that I'm working on is from 2004, it is possibly why I'm having this issue and that's why my Course ID was VARCHAR(255).

In any case, thanks for all help and I hope this helps someone with any similar problems (at least what look for in any bizarre but similar case).

If anyone has any suggestions, that could help me or others too. Thank you @Ocramius for all your help and attention.

**Comment by kimhemsoe** [comment]
Closing. Solution was found.
