### ISSUE TITLE
Remove dependency on symfony/framework-bundle

### ISSUE THREAD

**Issue by hason** [doctrine/DoctrineBundle#842]
Classes from framework bundle are used only for commands. I think they should be refactored.

**Comment by stof** [comment]
Well, technically, we also depend on services defined by FrameworkBundle (for the `annotation_reader` service at least).

But that's true we should work on refactoring these commands. Using DI rather than ContainerAwareCommand might be an option, as they are defined as services anyway. But we need to be careful about what to inject in them, to avoid issues with instantiating services too early that might break if the DB is not available. We should make sure that instantiating the command does not require connecting to the DB (otherwise, `bin/console list` could break as it needs to instantiate commands to get the details about them)

**Comment by chalasr** [comment]
ContainerAwareCommand has been deprecated for 4.2, I'm willing to help avoiding the incoming deprecation notice but I'm not sure what would be the right plan regarding BC. Ideally these commands should be lazy loaded

**Comment by chalasr** [comment]
#877 unlocks this for v2.0 (once the BC layer removed and the `symfony/console` requirement bumped to `^3.4|^4.0`).

**Comment by alcaeus** [comment]
After discussing this with @stof, I decided not to drop the dependency on symfony/framework-bundle: the bundle provides base classes like the generic annotation reader as well as the configuration for symfony/cache that is used in #948.
