### ISSUE TITLE
[RFC] Do not enforce instance of EntityRepository for repositories

### ISSUE THREAD

**Issue by Nek-** [doctrine/DoctrineBundle#856]
Some people don't want to extend the `EntityRepository` of Doctrine. But I understand we probably should check the type of the repository (even if Id like to not test it at all).

I suggest a middle solution. What about testing simply instance of `ObjectRepository`? This interface is not a big deal to implement and avoid to force people to extend `EntityRepository`.

**Comment by stof** [comment]
That's a requirement to respect the Doctrine ORM signature.

EntityRepository has a broader public API than the ObjectRepository interface, and `EntityManager::getRepository` guarantees to return a EntityRepository since years

**Comment by Nek-** [comment]
You mean it's implicit? Because the documentation suggests it another way. https://github.com/doctrine/doctrine2/blob/2.6/lib/Doctrine/ORM/EntityManager.php#L709

**Comment by stof** [comment]
Well, this documentation is weird, because in older versions, it was `EntityRepository` (the interface did not exist at that time). The phpdoc was updated when creating the interface, but the way it was written for the update would make it a BC break if you actually consider that extending `EntityRepository` is supported.

So I'm not sure whether this is considered as a supported use case by the ORM team.

**Comment by Nek-** [comment]
The main problem is that Symfony uses at many places the `getRepository()` ([see here](https://github.com/symfony/symfony/search?q=getRepository&unscoped_q=getRepository)) method and the [exception thrown](https://github.com/doctrine/DoctrineBundle/blob/a03386ccd8b72afa8b8f89c970b6de1fcc9d56e7/Repository/ContainerRepositoryFactory.php#L54) in case the entity repository does not inherit from `EntityRepository` become a problem.

It's true that back in 2.4 version of Doctrine, this interface didn't exist. But a compatibility layer can be written easily for that, isn't it?
