### ISSUE TITLE
Allow configuring AnnotationDriver::addExcludePaths

### ISSUE THREAD

**Issue by rainbow-alex** [doctrine/DoctrineBundle#911]
I can't configure this with the bundle, had to add a compiler pass and `addMethodCall` as a workaround.

**Comment by alcaeus** [comment]
I took a crack at adding this, but since most of the mapping logic is in `symfony/doctrine-bridge` I couldn't finish it. I have to postpone this to a future version, so you have to keep the compiler pass workaround for a bit longer.

I'll try to get this into doctrine-bridge in time for Symfony 4.4 though.

**Comment by dmaicher** [comment]
Can we close this considering the `AnnotationDriver` class is deprecated now?

**Comment by ostrolucky** [comment]
Indeed, let's do
