### ISSUE TITLE
Same entity managed on multiple entity managers

### ISSUE THREAD

**Issue by fabienlem** [doctrine/DoctrineBundle#925]
Hello,

I'm struggling with an use-case and I would like to get some feedback about it.

### Support Question

In an existing application, I have several entities that are managed by two distinct entity managers. This was done in order to allow synchronizing two versions of the same database.

With repository not used as services, it's quite easy to handle the situation:

```
$source = $sourceEntityManager->getRepository(Example::class)->find(1);
$target = $targetEntityManager->getRepository(Example::class)->find(1);
compare($source, $target);
```

But when used as services, repository objects use the first available entity manager:

```
$source = $sourceEntityManager->getRepository(Example::class)->find(1);
$target = $targetEntityManager->getRepository(Example::class)->find(1);
// both "find" will be performed on $sourceEntityManager
```

*Questions*

What could be a good approach to synchronize two version of the same database ?

Is there any workarround to get the code above work properly with repository classes used as services ?

**Comment by stof** [comment]
@fabienlem you would have to define separate service entity repositories for each of the EM. But for that, you would have to replace a lot of service definitions of the DoctrineBundle, because the bundle does not natively support that case (mapping the same entity in multiple managers has been considered a non-supported use case since years, and so was not added as a requirement of the ServiceEntityRepository implementation)

**Comment by fabienlem** [comment]
Ok @stof thanks a lot for your feedback!
