### ISSUE TITLE
New Method for querybuilder ->toArrayCollection

### ISSUE THREAD

**Issue by chiqui3d** [doctrine/DoctrineBundle#934]
Is it possible to add a new query builder method like `toArrayCollection`?

**Comment by SenseException** [comment]
Is this supposed to be a convenience method for `new ArrayCollection($qb->getQuery()->getResult())`?

**Comment by chiqui3d** [comment]
Yes that's what I'm doing now, but that way you don't have to convert and import a new library and you can do it directly: $qb->getQuery()->getArrayCollection()->first() or any other collection method.

**Comment by SenseException** [comment]
The Query Builder itself doesn't return any results because it only builds queries, which is why it won't get a method like suggested.

`Query` objects return results, but the form of the results depend on which hydration mode the user chooses. By default, `$qb->getQuery()->getResult()` returns an array with entity objects (`Query::HYDRATE_OBJECT`), which is its default hydration mode. Even the other result methods of `Query` like `getArrayResult()` or `getScalarResult()` are just helper methods, that differ only by the hydration mode constant.

Or in short: ORM already allows you to create a result of your choice like returning an `ArrayCollection`, when you create your own hydrator. It may look like `$qb->getQuery()->getResult('ArrayCollection')` in your code, after you create your custom hydrator for your project with that name.

More information about creating a custom hydrator:

* [DoctrineBundle configuration (search for "hydrator")](https://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html)
* [Hydration modes](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/dql-doctrine-query-language.html#hydration-modes)
* [Custom hydrations](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/dql-doctrine-query-language.html#custom-hydration-modes)

**Comment by chiqui3d** [comment]
Thank you for your reply is going to help me., it is clear that Doctrine does not intend to improve anything in years.

**Comment by SenseException** [comment]
Every week, bug fixes and/or features are getting merged in the projects of Doctrine. Please don't feel down if there won't be no query-result method in the Query Builder itself. Your created issue might help other people, who need a custom result that isn't shipped with DoctrineBundle or ORM by default and now might find a solution in a hydrator. Thank you for that help.

**Comment by chiqui3d** [comment]
In this tutorial is better explained to apply it with Symfony https://techpunch.co.uk/development/create-custom-doctrine2-hydrator-symfony2
