### ISSUE TITLE
MySQL has gone away

### ISSUE THREAD

**Issue by lyandr** [doctrine/DoctrineBundle#953]
Hello,

i'm using Doctrine DBAL and ORM on Symfony and i'm facing MySQL has gone away error since i migrated my application to a Cloud Foundry PaaS. And i'm facing this error with another script (Symfony command) that is an infinite loop that regularly check the database to do jobs that is also deployed the same Cloud Foundry PaaS. 

I try to do close and open connection every time but the problem is still present. And i tried to do the same script with PDO and i don't have this problem.

How can i know what is the problem with Doctrine and MySQL database? I can have information on the MySQL server database but i can't change the configuration.

Thank in advance for your help.

Regards,
Lyandr

**Comment by alcaeus** [comment]
Hi,

this is an issue tracker, reserved for issues with the integration of Doctrine ORM into Symfony. Your issue is a configuration problem where your server closes the connection due to inactivity. Please use the support channels (#doctrine or #support in Symfony Slack, #support in Doctrine Slack) or check Stack Overflow for possible solutions. I'm closing this here as there are plenty of questions regarding your problem on Stack Overflow, please check and/or ask there. Thank you!
