### ISSUE TITLE
After migration, doctrine deleted session table

### ISSUE THREAD

**Issue by JakubSzczesniak** [doctrine/DoctrineBundle#987]
I keep session in database. In my migrations I have code to create table:

```
        $this->addSql('CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL PRIMARY KEY, sess_data BYTEA NOT NULL, sess_time INTEGER NOT NULL, sess_lifetime INTEGER NOT NULL)
```

The problem is when I want to start another migration. `sessions` table is deleted in that case. Anyone knows why? In next migrations in default `up()` method is line `DROP TABLE sessions`

**Comment by dmaicher** [comment]
Seems this `session` table is not know to Doctrine. So if you auto-generate a diff between your Doctrine mapping and the database it will assume the `session` table is not needed.

Anyway I think this issue is more related to https://github.com/doctrine/migrations.

Maybe this is also useful: https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#manual-tables

**Comment by weaverryan** [comment]
Btw, there is a new feature in the bundle where migrations could “notify” doctrine that this table should be ignored from the scheme. The complicated part is that those other libraries don’t usually know which connection “session” should be ignored on... but I would like to figure out how to implement this stuff automatically.
